### ISSUE TITLE
minisign-gui is no longer compatible with the latest version 0.10 of minisign

### ISSUE THREAD

**Issue by JohnPlanetary** [TheChiefMeat/minisign-gui#2]
minisign-gui is no longer compatible with the latest version 0.10 of minisign.
I try it and doesn't work. I guess they must have change things on it.

**Comment by TheChiefMeat** [comment]
Hi again John :) 

Which parts of the application aren't working for you? I've noted that creating a key no longer works on Windows. 

A temporary fix for this bug is to manually create the 'minisign-keys' folder that normally should get generated, that way the 'Create' button should continue to function.

If you're having an other issues feel free to reply, and I'll see about fixing it more permanently with an update soon.

**Comment by TheChiefMeat** [comment]
I've added a pre-release version which should fix the above issue:

https://github.com/TheChiefMeat/minisign-gui/releases/tag/1.2.1

**Comment by JohnPlanetary** [comment]
Sorry for the delay I didn't get any notification on this topic from github, that is why I took so much time to answer.

I've tested "1.2.1" and is still giving a error, when attempting to run it.

Traceback (most recent call last):
  File "minisign-gui.pyw", line 10, in <module>
  File "tkinter\__init__.py", line 2109, in wm_iconbitmap
_tkinter.TclError: bitmap "C:\Users\TheChiefMeat\Documents\Git\minisign-gui\assets\app.ico" not defined

![error](https://user-images.githubusercontent.com/57976376/207129060-ab15bba6-76e2-4eed-af46-e94ea0868131.jpg)
